export const GET_ALL_WORKERS = 'GET_ALL_WORKERS';
export const GET_ALL_WORKERS_SUCCESS = 'GET_ALL_WORKERS_SUCCESS';
export const GET_ALL_WORKERS_FAIL = 'GET_ALL_WORKERS_FAIL';

export const CREATE_WORKER = 'CREATE_WORKER';
export const CREATE_WORKER_SUCCESS = 'CREATE_WORKER_SUCCESS';
export const CREATE_WORKER_FAIL = 'CREATE_WORKER_FAIL';

export const REMOVE_WORKER = 'REMOVE_WORKER';
export const REMOVE_WORKER_SUCCESS = 'REMOVE_WORKER_SUCCESS';
export const REMOVE_WORKER_FAIL = 'REMOVE_WORKER_FAIL';
